name: GitHub Actions Build and Deploy

on:
  push:
    branches:
      - gaoyan/dev # 这里只配置了master分支，所以只有推送master分支才会触发以下任务

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ci-${{ github.ref }}

    steps:
      - name: Checkout ️
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.0

      - name: Install and Build   # 安装依赖、打包，如果提前已打包好无需这一步
          # 安装 Node 之后就可以执行构建脚本
        run: |
          npm install yarn -g
          yarn
          yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.TOKEN }}
          branch: gh-pages
          folder: dist
